In [50]:
import os
import json
from pathlib import Path
import pandas as pd
import glob
import numpy as np
import pprint
import requests
from datetime import datetime
import time
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.1.153 Yowser/2.5 Safari/537.36'}

In [51]:
url = "https://data.europarl.europa.eu/api/v2/meetings"
url2 = "https://data.europarl.europa.eu/api/v2/meetings?year=2025&format=application/ld+json"
url3 = "https://data.europarl.europa.eu/api/v2/meetings?year=2026&format=application/ld+json"
url4 = "https://data.europarl.europa.eu/api/v2/meetings?year=2023&format=application/ld+json"
#not useful url_eli = "https://data.europarl.europa.eu/api/v2/eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939931&format=application/ld+json"
params = {
    "year": "2024",
    "format": "application/ld+json"
}

In [40]:
resp = requests.get(url, headers=headers, params=params)
data = resp.json()

In [41]:
data.keys()

dict_keys(['data', '@context'])

In [42]:
all_meetings = data["data"]
print(len(all_meetings))
all_meetings

50

[{'id': 'eli/dl/event/MTG-PL-2024-01-15',
  'type': 'Activity',
  'activity_date': '2024-01-15',
  'activity_end_date': '2024-01-15T23:00:00+01:00',
  'activity_id': 'MTG-PL-2024-01-15',
  'activity_label': {'hu': '2024. január 15., hétfő',
   'sv': 'Måndagen den 15 januari 2024',
   'el': 'Δευτέρα 15 Ιανουαρίου 2024',
   'lt': 'Pirmadienis, 2024 m. sausio 15 d.',
   'fi': 'Maanantai 15. tammikuuta 2024',
   'da': 'Mandag den 15. januar 2024',
   'ga': 'Dé Luain, 15 Eanáir 2024',
   'it': 'Lunedì 15 gennaio 2024',
   'es': 'Lunes 15 de enero de 2024',
   'et': 'Esmaspäev, 15. jaanuar 2024',
   'ro': 'Luni, 15 ianuarie 2024',
   'cs': 'Pondělí, 15. ledna 2024',
   'fr': 'Lundi 15 janvier 2024',
   'en': 'Monday, 15 January 2024',
   'sl': 'Ponedeljek, 15. januar 2024',
   'bg': 'Понеделник, 15 януари 2024',
   'hr': 'ponedjeljak, 15. siječnja 2024.',
   'sk': 'Pondelok, 15. januára 2024',
   'lv': 'Pirmdiena, 2024. gada 15. janvāris',
   'nl': 'Maandag 15 januari 2024',
   'mt': "It-Tnejn, 15 ta' Jannar 2024",
   'de': 'Montag, 15. Januar 2024',
   'pt': 'Segunda-feira, 15 de Janeiro de 2024',
   'pl': 'Poniedziałek, 15 stycznia 2024'},
  'activity_start_date': '2024-01-15T01:00:00+01:00',
  'consists_of': ['eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-14',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-22',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-CHA-2',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-2',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-6',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000003',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000001',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-16',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-18',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-5',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000007',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000006',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-13',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-12',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-150124',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-10',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-CHA-1',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-CHA-3',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-19',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-15',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-17',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-23',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-CHA-4',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000005',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-21',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-20',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-3',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-4',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000004',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-11',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-1',
   'eli/dl/event/MTG-PL-2024-01-15-VOT-ITM-000002',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-7',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-9',
   'eli/dl/event/MTG-PL-2024-01-15-PVCRE-ITM-8'],
  'documented_by_a_realization_of': ['eli/dl/doc/OJQ-9-2024-01-15'],
  'had_activity_type': 'def/ep-activities/PLENARY_SITTING',
  'had_excused_person': ['person/197683',
   'person/197579',
   'person/125030',
   'person/197842',
   'person/198183',
   'person/197690',
   'person/125025',
   'person/197396',
   'person/197422',
   'person/124770',
   'person/197478',
   'person/5392',
   'person/132366',
   'person/197457',
   'person/36392',
   'person/96775',
   'person/197788'],
  'had_participant_person': ['person/99283',
   'person/88882',
   'person/124807',
   'person/202073',
   'person/204346',
   'person/197843',
   'person/197426',
   'person/23868',
   'person/125046',
   'person/185974',
   'person/197472',
   'person/245018',
   'person/197528',
   'person/124856',
   'person/204332',
   'person/197623',
   'person/96880',
   'person/124936',
   'person/192635',
   'person/28297',
   'person/197395',
   'person/96779',
   'person/197439',
   'person/197544',
   'person/197657',
   'person/197425',
   'person/197629',
   'person/125067',
   'person/197455',
   'person/199996',
   'person/197838',
   'person/197441',
   'person/2323',
   'person/27714',
   'person/229352',
   'person/197771',
   'person/124715',
   'person/197800',
   'person/197709',
   'person/4289',
   'person/197935',
   'person/124700',
   'person/193273',
   'person/96808',
   'person/182995',
   'person/58766',
   'person/125706',
   'person/237465',
   'person/40599',
   'person/197549',
   'person/205452',
   'person/197564',
   'person/124802',
   'person/197410',
   'person/2341',
   'person/197641',
   'person/28586',
   'person/197742',
   'person/197675',
   'person/243912',
   'person/197390',
   'person/197446',
   'person/112744',
   'person/197889',
   'person/236052',
   'person/96812',
   'person/136236',
   'person/197773',
   'person/1909',
   'person/197438',
   'person/197802',
   'person/1927',
   'person/120478',
   'person/189525',
   'person/197808',
   'person/197677',
   'person/106936',
   'person/94649',
   'person/124877',
   'person/125004',
   'person/129073',
   'person/197791',
   'person/197585',
   'person/239256',
   'person/37312',
   'person/197462',
   'person/239271',
   'person/197695',
   'person/197518',
   'person/197662',
   'person/125128',
   'person/197571',
   'person/197763',
   'person/197654',
   'person/124812',
   'person/249443',
   'person/245858',
   'person/197475',
   'person/124992',
   'person/124701',
   'person/28353',
   'person/204335',
   'person/197577',
   'person/197461',
   'person/204418',
   'person/197687',
   'person/197398',
   'person/198329',
   'person/125023',
   'person/197480',
   'person/197536',
   'person/124833',
   'person/28400',
   'person/190713',
   'person/197467',
   'person/191693',
   'person/197458',
   'person/236050',
   'person/96668',
   'person/197606',
   'person/251324',
   'person/124835',
   'person/96772',
   'person/209896',
   'person/101039',
   'person/250918',
   'person/197520',
   'person/96991',
   'person/96756',
   'person/197482',
   'person/197538',
   'person/96653',
   'person/197556',
   'person/124693',
   'person/197402',
   'person/197828',
   'person/24505',
   'person/197503',
   'person/204443',
   'person/197621',
   'person/197734',
   'person/28347',
   'person/185341',
   'person/96681',
   'person/197572',
   'person/197488',
   'person/124850',
   'person/197781',
   'person/197408',
   'person/197608',
   'person/197423',
   'person/189065',
   'person/124692',
   'person/125043',
   'person/187917',
   'person/197502',
   'person/250538',
   'person/86793',
   'person/218347',
   'person/124713',
   'person/197780',
   'person/249603',
   'person/228604',
   'person/197541',
   'person/247709',
   'person/124777',
   'person/197651',
   'person/197794',
   'person/96932',
   'person/197459',
   'person/197626',
   'person/125068',
   'person/124884',
   'person/197786',
   'person/197574',
   'person/197618',
   'person/5729',
   'person/197566',
   'person/28288',
   'person/197646',
   'person/197430',
   'person/202352',
   'person/125109',
   'person/124704',
   'person/28219',
   'person/124784',
   'person/24942',
   'person/197444',
   'person/72779',
   'person/28399',
   'person/197392',
   'person/96810',
   'person/28224',
   'person/124973',
   'person/197754',
   'person/197414',
   'person/118859',
   'person/197645',
   'person/125012',
   'person/135511',
   'person/197728',
   'person/197584',
   'person/239255',
   'person/197679',
   'person/112748',
   'person/197443',
   'person/249826',
   'person/197510',
   'person/197777',
   'person/238639',
   'person/250235',
   'person/197648',
   'person/38420',
   'person/247737',
   'person/197587',
   'person/208722',
   'person/197731',
   'person/124734',
   'person/197512',
   'person/197682',
   'person/28226',
   'person/198176',
   'person/4246',
   'person/197638',
   'person/197589',
   'person/197817',
   'person/197586',
   'person/209091',
   'person/197699',
   'person/188945',
   'person/128483',
   'person/197663',
   'person/237320',
   'person/197767',
   'person/96801',
   'person/28294',
   'person/229839',
   'person/197822',
   'person/197764',
   'person/124705',
   'person/96830',
   'person/124785',
   'person/197835',
   'person/197495',
   'person/197766',
   'person/183338',
   'person/197415',
   'person/124837',
   'person/214839',
   'person/198096',
   'person/190519',
   'person/197530',
   'person/228286',
   'person/197827',
   'person/28429',
   'person/125038',
   'person/197464',
   'person/124771',
   'person/197631',
   'person/197525',
   'person/4267',
   'person/197591',
   'person/197522',
   'person/38511',
   'person/4344',
   'person/197778',
   'person/197769',
   'person/197607',
   'person/197400',
   'person/190518',
   'person/221463',
   'person/125042',
   'person/96787',
   'person/197391',
   'person/197497',
   'person/125237',
   'person/197417',
   'person/197435',
   'person/197540',
   'person/124821',
   'person/197829',
   'person/204334',
   'person/197500',
   'person/123562',
   'person/125045',
   'person/125063',
   'person/112747',
   'person/96791',
   'person/197451',
   'person/197527',
   'person/96998',
   'person/197489',
   'person/23699',
   'person/197610',
   'person/35016',
   'person/197848',
   'person/197427',
   'person/197543',
   'person/99945',
   'person/197863',
   'person/2054',
   'person/28619',
   'person/124866',
   'person/125104',
   'person/96934',
   'person/58789',
   'person/197628',
   'person/197519',
   'person/124934',
   'person/124586',
   'person/96820',
   'person/197545',
   'person/124710',
   'person/197718',
   'person/197542',
   'person/197655',
   'person/112611',
   'person/197798',
   'person/197505',
   'person/204336',
   'person/96933',
   'person/183793',
   'person/197627',
   'person/96725',
   'person/125065',
   'person/197720',
   'person/28340',
   'person/197578',
   'person/204419',
   'person/22858',
   'person/197671',
   'person/98582',
   'person/28390',
   'person/125214',
   'person/197412',
   'person/197537',
   'person/197756',
   'person/243979',
   'person/197429',
   'person/197868',
   'person/197563',
   'person/197647',
   'person/125001',
   'person/197870',
   'person/124799',
   'person/124766',
   'person/197722',
   'person/125106',
   'person/197448',
   'person/197804',
   'person/218349',
   'person/197445',
   'person/124873',
   'person/124822',
   'person/130256',
   'person/197743',
   'person/28161',
   'person/197740',
   'person/197691',
   'person/197514',
   'person/124872',
   'person/124806',
   'person/197432',
   'person/127096',
   'person/197557',
   'person/96761',
   'person/197539',
   'person/197650',
   'person/124891',
   'person/198490',
   'person/239258',
   'person/96899',
   'person/197717',
   'person/197697',
   'person/24594',
   'person/197806',
   'person/96646',
   'person/124738',
   'person/197668',
   'person/197573',
   'person/124735',
   'person/124722',
   'person/197394',
   'person/5565',
   'person/204400',
   'person/1917',
   'person/239257',
   'person/197463',
   'person/197770',
   'person/197795',
   'person/197550',
   'person/209140',
   'person/124834',
   'person/124929',
   'person/125021',
   'person/124996',
   'person/197534',
   'person/96837',
   'person/114268',
   'person/197468',
   'person/197635',
   'person/197465',
   'person/197470',
   'person/204421',
   'person/197526',
   'person/197670',
   'person/96829',
   'person/23816',
   'person/197824',
   'person/236051',
   'person/183916',
   'person/124988',
   'person/96868',
   'person/197772',
   'person/213330',
   'person/197404',
   'person/197401',
   'person/197840',
   'person/129164',
   'person/122978',
   'person/237224',
   'person/124760',
   'person/204420',
   'person/101585',
   'person/249284',
   'person/197483',
   'person/96776',
   'person/23768',
   'person/39725',
   'person/197403',
   'person/197504',
   'person/125064',
   'person/230085',
   'person/192634',
   'person/197513',
   'person/29579',
   'person/88715',
   'person/197782',
   'person/204733',
   'person/23781',
   'person/124712',
   'person/197406',
   'person/197849',
   'person/1892',
   'person/96852',
   'person/96709',
   'person/28266',
   'person/28372',
   'person/197421',
   'person/197507',
   'person/23712',
   'person/197818',
   'person/197576',
   'person/96780',
   'person/197440',
   'person/34578',
   'person/96711',
   'person/185619',
   'person/197785',
   'person/124714',
   'person/244571',
   'person/28122',
   'person/197546',
   'person/125093',
   'person/124696',
   'person/239972',
   'person/197490',
   'person/197506',
   'person/96952',
   'person/239262',
   'person/197836',
   'person/96713',
   'person/197580',
   'person/197787',
   'person/197496',
   'person/197784',
   'person/197616',
   'person/197416',
   'person/132191',
   'person/197567',
   'person/185771',
   'person/202036',
   'person/96936',
   'person/197531',
   'person/33997',
   'person/204449',
   'person/197632',
   'person/206158',
   'person/96922',
   'person/197805',
   'person/96891',
   'person/4560',
   'person/96811',
   'person/124861',
   'person/124808',
   'person/197559',
   'person/124708',
   'person/197634',
   'person/237779',
   'person/124985',
   'person/197473',
   'person/197711',
   'person/28346',
   'person/124747',
   'person/197582',
   'person/197498',
   'person/28150',
   'person/197418',
   'person/95074',
   'person/130833',
   'person/197436',
   'person/197649',
   'person/226260',
   'person/1992',
   'person/197819',
   'person/197588',
   'person/251268',
   'person/197452',
   'person/124781',
   'person/125670',
   'person/197665',
   'person/124875',
   'person/247735',
   'person/197831',
   'person/124739',
   'person/124726',
   'person/197491',
   'person/197680',
   'person/197611',
   'person/212855',
   'person/124867',
   'person/197596',
   'person/96734',
   'person/197460',
   'person/118949',
   'person/197516',
   'person/124844',
   'person/229519',
   'person/96750',
   'person/197765',
   'person/197719',
   'person/28269',
   'person/197532',
   'person/197799',
   'person/126644',
   'person/202351',
   'person/96885',
   'person/197672',
   'person/124862',
   'person/197826',
   'person/236053',
   'person/197493',
   'person/28223',
   'person/124831',
   'person/197413',
   'person/124709',
   'person/97236',
   'person/197523',
   'person/197825',
   'person/197839',
   'person/234344',
   'person/197619',
   'person/197419',
   'person/96752',
   'person/97058',
   'person/197701',
   'person/197405',
   'person/197552',
   'person/197844',
   'person/197841',
   'person/190464',
   'person/197529',
   'person/124887',
   'person/28615',
   'person/197792',
   'person/197595',
   'person/197624',
   'person/197692',
   'person/197515',
   'person/97968',
   'person/4746'],
  'number_of_attendees': 581,
  'parliamentary_term': 'org/ep-9',
  'recorded_in_a_realization_of': ['eli/dl/doc/PV-9-2024-01-15-ATT',
   'eli/dl/doc/PV-9-2024-01-15-RCV',
   'eli/dl/doc/PV-9-2024-01-15',
   'eli/dl/doc/CRE-9-2024-01-15',
   'eli/dl/doc/PV-9-2024-01-15-VOT'],
  'hasLocality': 'http://publications.europa.eu/resource/authority/place/FRA_SXB'},
 {'id': 'eli/dl/event/MTG-PL-2024-01-16',
  'type': 'Activity',
  'activity_date': '2024-01-16',
  'activity_end_date': '2024-01-16T23:00:00+01:00',
  'activity_id': 'MTG-PL-2024-01-16',
  'activity_label': {'da': 'Tirsdag den 16. januar 2024',
   'mt': "It-Tlieta, 16 ta' Jannar 2024",
   'ga': 'Dé Máirt, 16 Eanáir 2024',
   'hu': '2024. január 16., kedd',
   'sk': 'Utorok, 16. januára 2024',
   'es': 'Martes 16 de enero de 2024',
   'de': 'Dienstag, 16. Januar 2024',
   'it': 'Martedì 16 gennaio 2024',
   'lv': 'Otrdiena, 2024. gada 16. janvāris',
   'fr': 'Mardi 16 janvier 2024',
   'ro': 'Marţi, 16 ianuarie 2024',
   'cs': 'Úterý, 16. ledna 2024',
   'en': 'Tuesday, 16 January 2024',
   'pt': 'Terça-feira, 16 de Janeiro de 2024',
   'hr': 'utorak, 16. siječnja 2024.',
   'et': 'Teisipäev, 16. jaanuar 2024',
   'bg': 'Втoрник, 16 януари 2024',
   'sl': 'Torek, 16. januar 2024',
   'el': 'Τρίτη 16 Ιανουαρίου 2024',
   'lt': 'Antradienis, 2024 m. sausio 16 d.',
   'pl': 'Wtorek, 16 stycznia 2024',
   'nl': 'Dinsdag 16 januari 2024',
   'fi': 'Tiistai 16. tammikuuta 2024',
   'sv': 'Tisdagen den 16 januari 2024'},
  'activity_start_date': '2024-01-16T01:00:00+01:00',
  'consists_of': ['eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-11',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939925',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939908',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-4',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-20',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939947',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939920',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-8',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-4',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-7',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-10',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939932',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-17',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-3',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939928',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-13',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-2',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939927',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-6',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-16',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939946',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-2',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-12',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-5',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-22',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-19',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-1',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-8',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-24',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-1',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939922',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939903',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-21',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939939',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-9',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939938',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-5',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-23',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939937',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-18',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939918',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-14',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-7',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-3',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-CHA-6',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-9',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939910',
   'eli/dl/event/MTG-PL-2024-01-16-VOT-ITM-939916',
   'eli/dl/event/MTG-PL-2024-01-16-PVCRE-ITM-15'],
  'documented_by_a_realization_of': ['eli/dl/doc/OJQ-9-2024-01-16'],
  'had_activity_type': 'def/ep-activities/PLENARY_SITTING',
  'had_excused_person': ['person/36392',
   'person/125030',
   'person/197478',
   'person/125025',
   'person/5392',
   'person/197457',
   'person/197690',
   'person/124770',
   'person/197683',
   'person/132366',
   'person/197788',
   'person/197396',
   'person/197842',
   'person/197579',
   'person/197422',
   'person/96775',
   'person/198183'],
  'had_participant_person': ['person/125214',
   'person/197754',
   'person/96752',
   'person/197552',
   'person/96933',
   'person/197627',
   'person/96711',
   'person/197826',
   'person/124873',
   'person/236053',
   'person/98582',
   'person/28223',
   'person/250235',
   'person/197429',
   'person/125093',
   'person/101039',
   'person/124822',
   'person/204346',
   'person/197648',
   'person/124709',
   'person/130256',
   'person/197722',
   'person/239262',
   'person/96880',

In [6]:
#We now want to keep all meetings held on thursdays.
thursday_meetings = []
#Looking for the word "Thursday in the activity_label was unreliable
#We try using the datetime module instead.
for meeting in all_meetings:
    date_str = meeting.get("activity_date", {})

    if date_str:
        date_obj = datetime.fromisoformat(date_str)
        if date_obj.weekday() == 3:
            thursday_meetings.append(meeting)

In [7]:
len(thursday_meetings)

14

In [8]:
resp2 = requests.get(url2, headers=headers, params=params)
data2 = resp2.json()
data2.keys()

dict_keys(['data', '@context'])

In [9]:
resp3 = requests.get(url3, headers=headers, params=params)
data3 = resp3.json()
data3.keys()

dict_keys(['data', '@context'])

In [10]:
resp4 = requests.get(url4, headers=headers, params=params)
data4 = resp4.json()
data4.keys()

dict_keys(['data', '@context'])

In [11]:
meetings2025 = data2["data"]
meetings2026 = data3["data"]
meetings2023 = data4["data"]

In [12]:
#Now we append the rest of the thursdsay meetings to our list.
for meeting in meetings2025:
    date_str = meeting.get("activity_date", {})

    if date_str:
        date_obj = datetime.fromisoformat(date_str)
        if date_obj.weekday() == 3:
            thursday_meetings.append(meeting)

for meeting in meetings2026:
    date_str = meeting.get("activity_date", {})

    if date_str:
        date_obj = datetime.fromisoformat(date_str)
        if date_obj.weekday() == 3:
            thursday_meetings.append(meeting)

In [13]:
for meeting in meetings2023:
    date_str = meeting.get("activity_date", {})

    if date_str:
        date_obj = datetime.fromisoformat(date_str)
        if date_obj.weekday() == 3:
            thursday_meetings.append(meeting)

In [14]:
len(thursday_meetings)

60

In [15]:
#Just checking how often they convene.
dates = [meeting["activity_date"] for meeting in thursday_meetings[0:9]]
print(dates)

['2024-01-18', '2024-01-25', '2024-02-08', '2024-02-29', '2024-03-14', '2024-04-11', '2024-04-25', '2024-07-18', '2024-09-19']

In [16]:
thursday_meetings

[{'id': 'eli/dl/event/MTG-PL-2024-01-18',
  'type': 'Activity',
  'activity_date': '2024-01-18',
  'activity_end_date': '2024-01-18T23:00:00+01:00',
  'activity_id': 'MTG-PL-2024-01-18',
  'activity_label': {'lt': 'Ketvirtadienis, 2024 m. sausio 18 d.',
   'hu': '2024. január 18., csütörtök',
   'pt': 'Quinta-feira, 18 de Janeiro de 2024',
   'sv': 'Torsdagen den 18 januari 2024',
   'sk': 'Štvrtok, 18. januára 2024',
   'da': 'Torsdag den 18. januar 2024',
   'it': 'Giovedì 18 gennaio 2024',
   'et': 'Neljapäev, 18. jaanuar 2024',
   'nl': 'Donderdag 18 januari 2024',
   'cs': 'Čtvrtek, 18. ledna 2024',
   'es': 'Jueves 18 de enero de 2024',
   'bg': 'Четвъртък, 18 януари 2024',
   'sl': 'Četrtek, 18. januar 2024',
   'en': 'Thursday, 18 January 2024',
   'ro': 'Joi, 18 ianuarie 2024',
   'fi': 'Torstai 18. tammikuuta 2024',
   'el': 'Πέμπτη 18 Ιανουαρίου 2024',
   'de': 'Donnerstag, 18. Januar 2024',
   'pl': 'Czwartek, 18 stycznia 2024',
   'hr': 'četvrtak, 18. siječnja 2024.',
   'ga': 'Déardaoin, 18 Eanáir 2024',
   'fr': 'Jeudi 18 janvier 2024',
   'mt': "Il-Ħamis, 18 ta' Jannar 2024",
   'lv': 'Ceturtdiena, 2024. gada 18. janvāris'},
  'activity_start_date': '2024-01-18T01:00:00+01:00',
  'consists_of': ['eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939931',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-5',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-4',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-1',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939943',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939969',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-12',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-11',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939933',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-7',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939803',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-6',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939945',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939926',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-CHA-1',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939976',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-14',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-CHA-4',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939907',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-13',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-10',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939935',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-9',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939934',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-8',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-CHA-3',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939975',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-CHA-2',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939974',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-15',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939965',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-3',
   'eli/dl/event/MTG-PL-2024-01-18-PVCRE-ITM-2',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939919',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939917',
   'eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939967'],
  'documented_by_a_realization_of': ['eli/dl/doc/OJQ-9-2024-01-18'],
  'had_activity_type': 'def/ep-activities/PLENARY_SITTING',
  'had_excused_person': ['person/197683',
   'person/197478',
   'person/132366',
   'person/125025',
   'person/5392',
   'person/197690',
   'person/197396',
   'person/36392',
   'person/124770',
   'person/96775',
   'person/197842',
   'person/197579',
   'person/197457',
   'person/125030',
   'person/247122',
   'person/197422',
   'person/197788',
   'person/198183'],
  'had_participant_person': ['person/4746',
   'person/197772',
   'person/244571',
   'person/23781',
   'person/197432',
   'person/124821',
   'person/125046',
   'person/125038',
   'person/209091',
   'person/197623',
   'person/197463',
   'person/124846',
   'person/197591',
   'person/243912',
   'person/96779',
   'person/198329',
   'person/197701',
   'person/125020',
   'person/197564',
   'person/197425',
   'person/245858',
   'person/197641',
   'person/197504',
   'person/228286',
   'person/197720',
   'person/96725',
   'person/197464',
   'person/197624',
   'person/124586',
   'person/234344',
   'person/218347',
   'person/197510',
   'person/238639',
   'person/204413',
   'person/197545',
   'person/197539',
   'person/124834',
   'person/125021',
   'person/214839',
   'person/1917',
   'person/197505',
   'person/204336',
   'person/197795',
   'person/197596',
   'person/124747',
   'person/197451',
   'person/197445',
   'person/22858',
   'person/197513',
   'person/4560',
   'person/23699',
   'person/95074',
   'person/226260',
   'person/197558',
   'person/2341',
   'person/198096',
   'person/124866',
   'person/58789',
   'person/124781',
   'person/28399',
   'person/197670',
   'person/197769',
   'person/96812',
   'person/197491',
   'person/197439',
   'person/197611',
   'person/136236',
   'person/202036',
   'person/124691',
   'person/197526',
   'person/197743',
   'person/97236',
   'person/197836',
   'person/236052',
   'person/131507',
   'person/197782',
   'person/197606',
   'person/124710',
   'person/197552',
   'person/23868',
   'person/135511',
   'person/124985',
   'person/197631',
   'person/96899',
   'person/197527',
   'person/125063',
   'person/96998',
   'person/23816',
   'person/249285',
   'person/28223',
   'person/197763',
   'person/130833',
   'person/197413',
   'person/202073',
   'person/124802',
   'person/124822',
   'person/33982',
   'person/197634',
   'person/96787',
   'person/204332',
   'person/4267',
   'person/197711',
   'person/37312',
   'person/197520',
   'person/197731',
   'person/124934',
   'person/218349',
   'person/96991',
   'person/38511',
   'person/4344',
   'person/96867',
   'person/197436',
   'person/197408',
   'person/197849',
   'person/96761',
   'person/249443',
   'person/197677',
   'person/197697',
   'person/197581',
   'person/30482',
   'person/40599',
   'person/204414',
   'person/205452',
   'person/250237',
   'person/249603',
   'person/125004',
   'person/197645',
   'person/197401',
   'person/96709',
   'person/114268',
   'person/123562',
   'person/24922',
   'person/193273',
   'person/197514',
   'person/28297',
   'person/96820',
   'person/197493',
   'person/197770',
   'person/125005',
   'person/197646',
   'person/197430',
   'person/124777',
   'person/239257',
   'person/233862',
   'person/197588',
   'person/106936',
   'person/197449',
   'person/28161',
   'person/197805',
   'person/197461',
   'person/197671',
   'person/197665',
   'person/124877',
   'person/107212',
   'person/197488',
   'person/197616',
   'person/125214',
   'person/197608',
   'person/124891',
   'person/197502',
   'person/239258',
   'person/191693',
   'person/197738',
   'person/125045',
   'person/197470',
   'person/96922',
   'person/28219',
   'person/197462',
   'person/197393',
   'person/197694',
   'person/96711',
   'person/236053',
   'person/88715',
   'person/96668',
   'person/251324',
   'person/229352',
   'person/197537',
   'person/197563',
   'person/118859',
   'person/124996',
   'person/124708',
   'person/28586',
   'person/197503',
   'person/125106',
   'person/237224',
   'person/124760',
   'person/124739',
   'person/197443',
   'person/197766',
   'person/124929',
   'person/197418',
   'person/124714',
   'person/197610',
   'person/124807',
   'person/124833',
   'person/197556',
   'person/197635',
   'person/197629',
   'person/197475',
   'person/185974',
   'person/197444',
   'person/237320',
   'person/197787',
   'person/197398',
   'person/96868',
   'person/197767',
   'person/204733',
   'person/96772',
   'person/209896',
   'person/198176',
   'person/197653',
   'person/96837',
   'person/28288',
   'person/125001',
   'person/197531',
   'person/96936',
   'person/96780',
   'person/204419',
   'person/124861',
   'person/197412',
   'person/247709',
   'person/129073',
   'person/124887',
   'person/197525',
   'person/130100',
   'person/197519',
   'person/197498',
   'person/124734',
   'person/197682',
   'person/197781',
   'person/197544',
   'person/197405',
   'person/197431',
   'person/239972',
   'person/238674',
   'person/197472',
   'person/197808',
   'person/28353',
   'person/28347',
   'person/237465',
   'person/197839',
   'person/23788',
   'person/197395',
   'person/197754',
   'person/197406',
   'person/239973',
   'person/197650',
   'person/199941',
   'person/125068',
   'person/96734',
   'person/94649',
   'person/192635',
   'person/197695',
   'person/128483',
   'person/96891',
   'person/197573',
   'person/250235',
   'person/197538',
   'person/213330',
   'person/197848',
   'person/125093',
   'person/124709',
   'person/28372',
   'person/204335',
   'person/197722',
   'person/237779',
   'person/96885',
   'person/197742',
   'person/204420',
   'person/197512',
   'person/209140',
   'person/197822',
   'person/197419',
   'person/185619',
   'person/124808',
   'person/197567',
   'person/4246',
   'person/132191',
   'person/197709',
   'person/202352',
   'person/197400',
   'person/197841',
   'person/120478',
   'person/189525',
   'person/28619',
   'person/239255',
   'person/197717',
   'person/125042',
   'person/197586',
   'person/182995',
   'person/204421',
   'person/251249',
   'person/197447',
   'person/197663',
   'person/124875',
   'person/96747',
   'person/197532',
   'person/197870',
   'person/126644',
   'person/239256',
   'person/124856',
   'person/197935',
   'person/125043',
   'person/197448',
   'person/197835',
   'person/197804',
   'person/197889',
   'person/197460',
   'person/198063',
   'person/197391',
   'person/197692',
   'person/236051',
   'person/124862',
   'person/124988',
   'person/197657',
   'person/131580',
   'person/197501',
   'person/125104',
   'person/197791',
   'person/197441',
   'person/2323',
   'person/197619',
   'person/229839',
   'person/249284',
   'person/28226',
   'person/197416',
   'person/127096',
   'person/97058',
   'person/124831',
   'person/96933',
   'person/197473',
   'person/197467',
   'person/204449',
   'person/197627',
   'person/96829',
   'person/124738',
   'person/197779',
   'person/197765',
   'person/88882',
   'person/197481',
   'person/197435',
   'person/197429',
   'person/28141',
   'person/197651',
   'person/124771',
   'person/197628',
   'person/197818',
   'person/124700',
   'person/197574',
   'person/197832',
   'person/197549',
   'person/28122',
   'person/1927',
   'person/197719',
   'person/212855',
   'person/204346',
   'person/190713',
   'person/130256',
   'person/197699',
   'person/197455',
   'person/199996',
   'person/197621',
   'person/124844',
   'person/197523',
   'person/72779',
   'person/197496',
   'person/197680',
   'person/197773',
   'person/197542',
   'person/197403',
   'person/112611',
   'person/197423',
   'person/240478',
   'person/197798',
   'person/197458',
   'person/96791',
   'person/96808',
   'person/24594',
   'person/197615',
   'person/124713',
   'person/124812',
   'person/96698',
   'person/197543',
   'person/197404',
   'person/197845',
   'person/124799',
   'person/250918',
   'person/197392',
   'person/197687',
   'person/197786',
   'person/197571',
   'person/197511',
   'person/35016',
   'person/197536',
   'person/125012',
   'person/197792',
   'person/125067',
   'person/251268',
   'person/38398',
   'person/197740',
   'person/96713',
   'person/197452',
   'person/197668',
   'person/192634',
   'person/101585',
   'person/96681',
   'person/124872',
   'person/197417',
   'person/96810',
   'person/197483',
   'person/23768',
   'person/124806',
   'person/197559',
   'person/96739',
   'person/197638',
   'person/124867',
   'person/190464',
   'person/840',
   'person/197721',
   'person/187917',
   'person/118949',
   'person/124873',
   'person/124835',
   'person/101039',
   'person/197530',
   'person/2054',
   'person/197827',
   'person/197840',
   'person/197819',
   'person/124701',
   'person/185341',
   'person/197734',
   'person/197585',
   'person/247737',
   'person/197446',
   'person/96903',
   'person/204418',
   'person/27714',
   'person/197662',
   'person/125128',
   'person/197802',
   'person/197649',
   'person/124696',
   'person/28400',
   'person/24505',
   'person/197728',
   'person/197553',
   'person/124992',
   'person/124704',
   'person/197632',
   'person/197578',
   'person/197518',
   'person/250538',
   'person/197497',
   'person/228604',
   'person/99283',
   'person/197702',
   'person/28224',
   'person/197414',
   'person/197434',
   'person/197459',
   'person/197465',
   'person/193292',
   'person/28346',
   'person/197675',
   'person/122978',
   'person/112744',
   'person/197440',
   'person/34578',
   'person/29579',
   'person/197777',
   'person/197394',
   'person/5729',
   'person/197546',
   'person/197566',
   'person/197427',
   'person/197506',
   'person/125109',
   'person/96833',
   'person/239260',
   'person/96932',
   'person/197626',
   'person/96952',
   'person/197698',
   'person/112747',
   'person/197572',
   'person/124973',
   'person/197547',
   'person/125023',
   'person/197480',
   'person/190518',
   'person/96653',
   'person/197507',
   'person/96646',
   'person/28340',
   'person/197515',
   'person/96801',
   'person/236050',
   'person/28294',
   'person/197494',
   'person/28269',
   'person/197771',
   'person/243979',
   'person/1892',
   'person/197540',
   'person/96852',
   'person/190519',
   'person/202351',
   'person/197421',
   'person/197829',
   'person/124692',
   'person/197500',
   'person/197672',
   'person/183338',
   'person/96756',
   'person/197607',
   'person/96776',
   'person/197541',
   'person/197402',
   'person/197843',
   'person/197863',
   'person/124693',
   'person/125064',
   'person/230085',
   'person/204443',
   'person/24942',
   'person/188945',
   'person/197390',
   'person/197691',
   'person/197784',
   'person/197764',
   'person/124712',
   'person/197534',
   'person/197844',
   'person/189065',
   'person/124705',
   'person/197589',
   'person/197529',
   'person/125065',
   'person/197595',
   'person/183916',
   'person/249826',
   'person/97968',
   'person/197415',
   'person/5565',
   'person/96750',
   'person/197557',
   'person/28266',
   'person/197636',
   'person/23712',
   'person/197582',
   'person/239271',
   'person/197522',
   'person/124936',
   'person/197778',
   'person/197438',
   'person/28150',
   'person/197482',
   'person/197654',
   'person/197490',
   'person/129164',
   'person/197679',
   'person/197817',
   'person/124766',
   'person/112748',
   'person/247735',
   'person/197577',
   'person/197831',
   'person/204416',
   'person/197718',
   'person/197800',
   'person/197647',
   'person/190774',
   'person/185771',
   'person/198490',
   'person/221463',
   'person/197551',
   'person/33997',
   'person/124785',
   'person/124884',
   'person/86793',
   'person/197516',
   'person/125706',
   'person/197495',
   'person/197489',
   'person/229519'],
  'number_of_attendees': 586,
  'parliamentary_term': 'org/ep-9',
  'recorded_in_a_realization_of': ['eli/dl/doc/PV-9-2024-01-18-ATT',
   'eli/dl/doc/PV-9-2024-01-18',
   'eli/dl/doc/PV-9-2024-01-18-VOT',
   'eli/dl/doc/CRE-9-2024-01-18',
   'eli/dl/doc/PV-9-2024-01-18-RCV'],
  'hasLocality': 'http://publications.europa.eu/resource/authority/place/FRA_SXB'},
 {'id': 'eli/dl/event/MTG-PL-2024-01-25',
  'type': 'Activity',
  'activity_date': '2024-01-25',
  'activity_end_date': '2024-01-25T23:00:00+01:00',
  'activity_id': 'MTG-PL-2024-01-25',
  'activity_label': {'de': 'Donnerstag, 25. Januar 2024',
   'it': 'Giovedì 25 gennaio 2024',
   'mt': "Il-Ħamis, 25 ta' Jannar 2024",
   'fi': 'Torstai 25. tammikuuta 2024',
   'bg': 'Четвъртък, 25 януари 2024',
   'pl': 'Czwartek, 25 stycznia 2024',
   'es': 'Jueves 25 de enero de 2024',
   'hu': '2024. január 25., csütörtök',
   'sl': 'Četrtek, 25. januar 2024',
   'da': 'Torsdag den 25. januar 2024',
   'pt': 'Quinta-feira, 25 de Janeiro de 2024',
   'cs': 'Čtvrtek, 25. ledna 2024',
   'lt': 'Ketvirtadienis, 2024 m. sausio 25 d.',
   'el': 'Πέμπτη 25 Ιανουαρίου 2024',
   'sv': 'Torsdagen den 25 januari 2024',
   'fr': 'Jeudi 25 janvier 2024',
   'hr': 'četvrtak, 25. siječnja 2024.',
   'ga': 'Déardaoin, 25 Eanáir 2024',
   'et': 'Neljapäev, 25. jaanuar 2024',
   'en': 'Thursday, 25 January 2024',
   'ro': 'Joi, 25 ianuarie 2024',
   'lv': 'Ceturtdiena, 2024. gada 25. janvāris',
   'sk': 'Štvrtok, 25. januára 2024',
   'nl': 'Donderdag 25 januari 2024'},
  'activity_start_date': '2024-01-25T01:00:00+01:00',
  'consists_of': ['eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-5',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-1',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-7',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-6',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-2',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-CHA-1',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-8',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-3',
   'eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-4'],
  'documented_by_a_realization_of': ['eli/dl/doc/OJQ-9-2024-01-25'],
  'had_activity_type': 'def/ep-activities/PLENARY_SITTING',
  'had_excused_person': ['person/197579',
   'person/124770',
   'person/197396',
   'person/197690',
   'person/125030',
   'person/197671',
   'person/197632',
   'person/23816'],
  'had_participant_person': ['person/197840',
   'person/197782',
   'person/197728',
   'person/124802',
   'person/197843',
   'person/218347',
   'person/197810',
   'person/197589',
   'person/197398',
   'person/244571',
   'person/197698',
   'person/38511',
   'person/197534',
   'person/202073',
   'person/38398',
   'person/124822',
   'person/197401',
   'person/197863',
   'person/96653',
   'person/197511',
   'person/38595',
   'person/204332',
   'person/250918',
   'person/191693',
   'person/28141',
   'person/124714',
   'person/118949',
   'person/197662',
   'person/197842',
   'person/35016',
   'person/197800',
   'person/124856',
   'person/125046',
   'person/205452',
   'person/249603',
   'person/107212',
   'person/96725',
   'person/197680',
   'person/96932',
   'person/125064',
   'person/124806',
   'person/239260',
   'person/237224',
   'person/197431',
   'person/28223',
   'person/197519',
   'person/197553',
   'person/197538',
   'person/4746',
   'person/204413',
   'person/197436',
   'person/23768',
   'person/197405',
   'person/197573',
   'person/125104',
   'person/197792',
   'person/197777',
   'person/197647',
   'person/124973',
   'person/197470',
   'person/190464',
   'person/96899',
   'person/206158',
   'person/189065',
   'person/243912',
   'person/197446',
   'person/197802',
   'person/88882',
   'person/197765',
   'person/124766',
   'person/40599',
   'person/237465',
   'person/197767',
   'person/97968',
   'person/124877',
   'person/125670',
   'person/197817',
   'person/229839',
   'person/197638',
   'person/4246',
   'person/124693',
   'person/130100',
   'person/2341',
   'person/197596',
   'person/124700',
   'person/2054',
   'person/197634',
   'person/237320',
   'person/197455',
   'person/98582',
   'person/197541',
   'person/239973',
   'person/197577',
   'person/23868',
   'person/197650',
   'person/96903',
   'person/197691',
   'person/197571',
   'person/124692',
   'person/197711',
   'person/197822',
   'person/124738',
   'person/239972',
   'person/125004',
   'person/28586',
   'person/96885',
   'person/124785',
   'person/197731',
   'person/197448',
   'person/250572',
   'person/124708',
   'person/197526',
   'person/840',
   'person/96747',
   'person/197465',
   'person/197457',
   'person/124781',
   'person/197838',
   'person/24505',
   'person/197699',
   'person/5392',
   'person/124799',
   'person/124704',
   'person/197567',

In [43]:
all_meetings.extend(meetings2025)
all_meetings.extend(meetings2026)
all_meetings.extend(meetings2023)

In [47]:
len(all_meetings)
df_all = pd.DataFrame(all_meetings)
df_all.to_csv("all_meetings_raw.csv")

In [56]:
#To get a larger data set we're gonna add meetings from more years - all the way back to 2010,
#but skipping 2020-2022 because voting was remote during covid.
more_thursday_meetings = []
more_years_all_json_folder = "more_years_raw_all_meetings_jsons"
os.makedirs(more_years_all_json_folder, exist_ok=True)

# 2019 will be the real test year!
more_years = ["2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010"]

for year in more_years:
    print(f"\n[{year}] Fetching data from API...")
    url = "https://data.europarl.europa.eu/api/v2/meetings"

    # Removed the limit parameter to match your working 2025 code!
    params = {
        "year": year,
        "format": "application/ld+json"
    }
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            data = response.json()
            try:
                safe_filename = f"meetings_{year}.json"
                file_path = os.path.join(more_years_all_json_folder, safe_filename)
                with open(file_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=4)
            except Exception as save_err:
                print(f"  -> Warning: Could not save file for {year}: {save_err}")

            thursday_count = 0
            
            if "data" in data and isinstance(data["data"], list):
                
                for meeting in data["data"]:
                    date_str = meeting.get("activity_start_date") or meeting.get("activity_date")
                    if not date_str and isinstance(meeting.get("eli-dl:activity_date"), dict):
                        date_str = meeting["eli-dl:activity_date"].get("@value")
                    
                    if date_str:
                        clean_date = date_str.replace("Z", "+00:00")
                        # Fixed: Passing clean_date into the format instead of date_str
                        date_obj = datetime.fromisoformat(clean_date) 
                        
                        if date_obj.weekday() == 3:
                            more_thursday_meetings.append(meeting)
                            thursday_count += 1
    
                print(f"[{year}] Filtered: Found {thursday_count} Thursdays.")
                        
        time.sleep(0.5)

    except Exception as e:
        print(f"Something went wrong: {e}")

df_more_thursdays = pd.DataFrame(more_thursday_meetings)
print(f"\n--- FETCH COMPLETE ---")
print(f"Total historical Thursday meetings found: {len(df_more_thursdays)}")

if not df_more_thursdays.empty:
    print(df_more_thursdays.head())

[2019] Fetching data from API...
[2019] Filtered: Found 15 Thursdays.

[2018] Fetching data from API...
[2018] Filtered: Found 15 Thursdays.

[2017] Fetching data from API...
[2017] Filtered: Found 17 Thursdays.

[2016] Fetching data from API...
[2016] Filtered: Found 17 Thursdays.

[2015] Fetching data from API...
[2015] Filtered: Found 13 Thursdays.

[2014] Fetching data from API...
[2014] Filtered: Found 13 Thursdays.

[2013] Fetching data from API...

[2012] Fetching data from API...

[2011] Fetching data from API...

[2010] Fetching data from API...

--- FETCH COMPLETE ---
Total historical Thursday meetings found: 90
                               id      type  \
0  eli/dl/event/MTG-PL-2019-01-17  Activity
1  eli/dl/event/MTG-PL-2019-01-31  Activity
2  eli/dl/event/MTG-PL-2019-02-14  Activity
3  eli/dl/event/MTG-PL-2019-03-14  Activity
4  eli/dl/event/MTG-PL-2019-03-28  Activity

                                eli-dl:activity_date  \
0  {'@value': '2019-01-17T00:00:00+01:00', 'type'...
1  {'@value': '2019-01-31T00:00:00+01:00', 'type'...
2  {'@value': '2019-02-14T00:00:00+01:00', 'type'...
3  {'@value': '2019-03-14T00:00:00+01:00', 'type'...
4  {'@value': '2019-03-28T00:00:00+01:00', 'type'...

           activity_end_date        activity_id  \
0  2019-01-17T23:00:00+01:00  MTG-PL-2019-01-17
1  2019-01-31T23:00:00+01:00  MTG-PL-2019-01-31
2  2019-02-14T23:00:00+01:00  MTG-PL-2019-02-14
3  2019-03-14T23:00:00+01:00  MTG-PL-2019-03-14
4  2019-03-28T23:00:00+01:00  MTG-PL-2019-03-28

                                      activity_label  \
0  {'pt': 'Quinta-feira, 17 de Janeiro de 2019', ...
1  {'hu': '2019. január 31., csütörtök', 'lt': 'K...
2  {'lv': 'Ceturtdiena, 2019. gada 14. februāris'...
3  {'pt': 'Quinta-feira, 14 de Março de 2019', 'i...
4  {'el': 'Πέμπτη 28 Μαρτίου 2019', 'pl': 'Czwart...

         activity_start_date  \
0  2019-01-17T01:00:00+01:00
1  2019-01-31T01:00:00+01:00
2  2019-02-14T01:00:00+01:00
3  2019-03-14T01:00:00+01:00
4  2019-03-28T01:00:00+01:00

                                         consists_of  \
0  [eli/dl/event/MTG-PL-2019-01-17-VOT-ITM-763604...
1  [eli/dl/event/MTG-PL-2019-01-31-VOT-ITM-768760...
2  [eli/dl/event/MTG-PL-2019-02-14-VOT-ITM-770475...
3  [eli/dl/event/MTG-PL-2019-03-14-VOT-ITM-777923...
4  [eli/dl/event/MTG-PL-2019-03-28-VOT-ITM-781185...

  documented_by_a_realization_of                  had_activity_type  \
0  [eli/dl/doc/OJQ-8-2019-01-17]  def/ep-activities/PLENARY_SITTING
1  [eli/dl/doc/OJQ-8-2019-01-31]  def/ep-activities/PLENARY_SITTING
2  [eli/dl/doc/OJQ-8-2019-02-14]  def/ep-activities/PLENARY_SITTING
3  [eli/dl/doc/OJQ-8-2019-03-14]  def/ep-activities/PLENARY_SITTING
4  [eli/dl/doc/OJQ-8-2019-03-28]  def/ep-activities/PLENARY_SITTING

  parliamentary_term                                        hasLocality  \
0           org/ep-8  http://publications.europa.eu/resource/authori...
1           org/ep-8  http://publications.europa.eu/resource/authori...
2           org/ep-8  http://publications.europa.eu/resource/authori...
3           org/ep-8  http://publications.europa.eu/resource/authori...
4           org/ep-8  http://publications.europa.eu/resource/authori...

                        recorded_in_a_realization_of had_excused_person  \
0                                                NaN                NaN
1                                                NaN                NaN
2                                                NaN                NaN
3  [eli/dl/doc/PV-8-2019-03-14-RCV, eli/dl/doc/PV...                NaN
4  [eli/dl/doc/PV-8-2019-03-28-RCV, eli/dl/doc/PV...                NaN

  had_participant_person  number_of_attendees was_scheduled_in
0                    NaN                  NaN              NaN
1                    NaN                  NaN              NaN
2                    NaN                  NaN              NaN
3                    NaN                  NaN              NaN
4                    NaN                  NaN              NaN

In [18]:
df = pd.DataFrame(thursday_meetings)
df.to_csv("all_thursdays.csv")

In [1]:
df.head()

NameError: name 'df' is not defined

In [60]:
df_more_thursdays["activity_date"] = df_more_thursdays["eli-dl:activity_date"]

In [63]:
df_more_thursdays.drop(columns="eli-dl:activity_date", inplace=True)

In [64]:
df_more_thursdays.head(20)

,id,type,activity_end_date,activity_id,activity_label,activity_start_date,consists_of,documented_by_a_realization_of,had_activity_type,parliamentary_term,hasLocality,recorded_in_a_realization_of,had_excused_person,had_participant_person,number_of_attendees,was_scheduled_in,activity_date
0,eli/dl/event/MTG-PL-2019-01-17,Activity,2019-01-17T23:00:00+01:00,MTG-PL-2019-01-17,"{'pt': 'Quinta-feira, 17 de Janeiro de 2019', ...",2019-01-17T01:00:00+01:00,[eli/dl/event/MTG-PL-2019-01-17-VOT-ITM-763604...,[eli/dl/doc/OJQ-8-2019-01-17],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2019-01-17T00:00:00+01:00', 'type'..."
1,eli/dl/event/MTG-PL-2019-01-31,Activity,2019-01-31T23:00:00+01:00,MTG-PL-2019-01-31,"{'hu': '2019. január 31., csütörtök', 'lt': 'K...",2019-01-31T01:00:00+01:00,[eli/dl/event/MTG-PL-2019-01-31-VOT-ITM-768760...,[eli/dl/doc/OJQ-8-2019-01-31],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2019-01-31T00:00:00+01:00', 'type'..."
2,eli/dl/event/MTG-PL-2019-02-14,Activity,2019-02-14T23:00:00+01:00,MTG-PL-2019-02-14,"{'lv': 'Ceturtdiena, 2019. gada 14. februāris'...",2019-02-14T01:00:00+01:00,[eli/dl/event/MTG-PL-2019-02-14-VOT-ITM-770475...,[eli/dl/doc/OJQ-8-2019-02-14],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2019-02-14T00:00:00+01:00', 'type'..."
3,eli/dl/event/MTG-PL-2019-03-14,Activity,2019-03-14T23:00:00+01:00,MTG-PL-2019-03-14,"{'pt': 'Quinta-feira, 14 de Março de 2019', 'i...",2019-03-14T01:00:00+01:00,[eli/dl/event/MTG-PL-2019-03-14-VOT-ITM-777923...,[eli/dl/doc/OJQ-8-2019-03-14],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-8-2019-03-14-RCV, eli/dl/doc/PV...",NaN,NaN,NaN,NaN,"{'@value': '2019-03-14T00:00:00+01:00', 'type'..."
4,eli/dl/event/MTG-PL-2019-03-28,Activity,2019-03-28T23:00:00+01:00,MTG-PL-2019-03-28,"{'el': 'Πέμπτη 28 Μαρτίου 2019', 'pl': 'Czwart...",2019-03-28T01:00:00+01:00,[eli/dl/event/MTG-PL-2019-03-28-VOT-ITM-781185...,[eli/dl/doc/OJQ-8-2019-03-28],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-8-2019-03-28-RCV, eli/dl/doc/PV...",NaN,NaN,NaN,NaN,"{'@value': '2019-03-28T00:00:00+01:00', 'type'..."
5,eli/dl/event/MTG-PL-2019-04-04,Activity,2019-04-04T23:00:00+02:00,MTG-PL-2019-04-04,"{'es': 'Jueves 4 de abril de 2019', 'sk': 'Štv...",2019-04-04T01:00:00+02:00,[eli/dl/event/MTG-PL-2019-04-04-VOT-ITM-782577...,[eli/dl/doc/OJQ-8-2019-04-04],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-8-2019-04-04, eli/dl/doc/PV-8-2...",NaN,NaN,NaN,NaN,"{'@value': '2019-04-04T00:00:00+02:00', 'type'..."
6,eli/dl/event/MTG-PL-2019-04-18,Activity,2019-04-18T23:00:00+02:00,MTG-PL-2019-04-18,"{'et': 'Neljapäev, 18. aprill 2019', 'sl': 'Če...",2019-04-18T01:00:00+02:00,[eli/dl/event/MTG-PL-2019-04-18-VOT-ITM-786314...,[eli/dl/doc/OJQ-8-2019-04-18],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-8-2019-04-18, eli/dl/doc/PV-8-2...",NaN,NaN,NaN,NaN,"{'@value': '2019-04-18T00:00:00+02:00', 'type'..."
7,eli/dl/event/MTG-PL-2019-07-04,Activity,2019-07-04T23:00:00+02:00,MTG-PL-2019-07-04,"{'ro': 'Joi, 4 iulie 2019', 'sk': 'Štvrtok, 4....",2019-07-04T01:00:00+02:00,"[eli/dl/event/MTG-PL-2019-07-04-PVCRE-ITM-12, ...",[eli/dl/doc/OJQ-9-2019-07-04],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,[eli/dl/doc/PV-9-2019-07-04],"[person/125067, person/197542]","[person/197466, person/187917, person/197589, ...",709.0,NaN,"{'@value': '2019-07-04T00:00:00+02:00', 'type'..."
8,eli/dl/event/MTG-PL-2019-07-18,Activity,2019-07-18T23:00:00+02:00,MTG-PL-2019-07-18,"{'mt': 'Il-Ħamis, 18 ta' Lulju 2019', 'et': 'N...",2019-07-18T01:00:00+02:00,"[eli/dl/event/MTG-PL-2019-07-18-PVCRE-ITM-1, e...",[eli/dl/doc/OJQ-9-2019-07-18],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-07-18, eli/dl/doc/PV-9-2...","[person/197640, person/197799, person/124806, ...","[person/197678, person/123562, person/118859, ...",667.0,NaN,"{'@value': '2019-07-18T00:00:00+02:00', 'type'..."
9,eli/dl/event/MTG-PL-2019-09-19,Activity,2019-09-19T23:00:00+02:00,MTG-PL-2019-09-19,"{'lt': 'Ketvirtadienis, 2019 m. rugsėjo 19 d.'...",2019-09-19T01:00:00+02:00,"[eli/dl/event/MTG-PL-2019-09-19-PVCRE-ITM-4, e...",[eli/dl/doc/OJQ-9-2019-09-19],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-09-19-RCV, eli/dl/doc/PV...","[person/124985, person/197786, person/106936, ...","[person/197698, person/197439, person/197704, ...",680.0,NaN,"{'@value': '2019-09-19T00:00:00+02:00', 'type'..."
10,eli/dl/event/MTG-PL-2019-10-10,Activity,2019-10-10T23:00:00+02:00,MTG-PL-2019-10-10,"{'ro': 'Joi, 10 octombrie 2019', 'mt': 'Il-Ħam...",2019-10-10T01:00:00+02:00,"[eli/dl/event/MTG-PL-2019-10-10-PVCRE-ITM-8, e...",[eli/dl/doc/OJQ-9-2019-10-10],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-10-10-RCV, eli/dl/doc/PV...","[person/124973, person/197522, person/113892, ...","[person/112611, person/124766, person/197495, ...",616.0,NaN,"{'@value': '2019-10-10T00:00:00+02:00', 'type'..."
11,eli/dl/event/MTG-PL-2019-10-24,Activity,2019-10-24T23:00:00+02:00,MTG-PL-2019-10-24,"{'bg': 'Четвъртък, 24 октомври 2019', 'lv': 'C...",2019-10-24T01:00:00+02:00,"[eli/dl/event/MTG-PL-2019-10-24-PVCRE-ITM-5, e...",[eli/dl/doc/OJQ-9-2019-10-24],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-10-24-RCV, eli/dl/doc/PV...","[person/197543, person/197457, person/28297, p...","[person/197662, person/197527, person/188636, ...",659.0,NaN,"{'@value': '2019-10-24T00:00:00+02:00', 'type'..."
12,eli/dl/event/MTG-PL-2019-11-14,Activity,2019-11-14T23:00:00+01:00,MTG-PL-2019-11-14,"{'fi': 'Torstai 14. marraskuuta 2019', 'lv': '...",2019-11-14T01:00:00+01:00,"[eli/dl/event/MTG-PL-2019-11-14-PVCRE-ITM-1, e...",[eli/dl/doc/OJQ-9-2019-11-14],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-11-14, eli/dl/doc/PV-9-2...","[person/197459, person/197785, person/197720, ...","[person/96933, person/124992, person/197777, p...",612.0,NaN,"{'@value': '2019-11-14T00:00:00+01:00', 'type'..."
13,eli/dl/event/MTG-PL-2019-11-28,Activity,2019-11-28T23:00:00+01:00,MTG-PL-2019-11-28,"{'sv': 'Torsdagen den 28 november 2019', 'nl':...",2019-11-28T01:00:00+01:00,"[eli/dl/event/MTG-PL-2019-11-28-PVCRE-ITM-5, e...",[eli/dl/doc/OJQ-9-2019-11-28],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-11-28-RCV, eli/dl/doc/PV...","[person/197761, person/197612, person/197549, ...","[person/125004, person/197620, person/4289, pe...",671.0,NaN,"{'@value': '2019-11-28T00:00:00+01:00', 'type'..."
14,eli/dl/event/MTG-PL-2019-12-19,Activity,2019-12-19T23:00:00+01:00,MTG-PL-2019-12-19,"{'el': 'Πέμπτη 19 Δεκεμβρίου 2019', 'cs': 'Čtv...",2019-12-19T01:00:00+01:00,"[eli/dl/event/MTG-PL-2019-12-19-PVCRE-ITM-15, ...",[eli/dl/doc/OJQ-9-2019-12-19],def/ep-activities/PLENARY_SITTING,org/ep-9,http://publications.europa.eu/resource/authori...,"[eli/dl/doc/PV-9-2019-12-19, eli/dl/doc/PV-9-2...","[person/36392, person/113892, person/197542, p...","[person/197528, person/1909, person/124991, pe...",656.0,NaN,"{'@value': '2019-12-19T00:00:00+01:00', 'type'..."
15,eli/dl/event/MTG-PL-2018-01-18,Activity,2018-01-18T23:00:00+01:00,MTG-PL-2018-01-18,"{'mt': 'Il-Ħamis, 18 ta' Jannar 2018', 'it': '...",2018-01-18T01:00:00+01:00,[eli/dl/event/MTG-PL-2018-01-18-VOT-ITM-670670...,[eli/dl/doc/OJQ-8-2018-01-18],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2018-01-18T00:00:00+01:00', 'type'..."
16,eli/dl/event/MTG-PL-2018-02-08,Activity,2018-02-08T23:00:00+01:00,MTG-PL-2018-02-08,"{'hr': 'četvrtak, 8. veljače 2018.', 'sl': 'Če...",2018-02-08T01:00:00+01:00,[eli/dl/event/MTG-PL-2018-02-08-VOT-ITM-677162...,[eli/dl/doc/OJQ-8-2018-02-08],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2018-02-08T00:00:00+01:00', 'type'..."
17,eli/dl/event/MTG-PL-2018-03-01,Activity,2018-03-01T23:00:00+01:00,MTG-PL-2018-03-01,"{'el': 'Πέμπτη 1 Μαρτίου 2018', 'nl': 'Donderd...",2018-03-01T01:00:00+01:00,[eli/dl/event/MTG-PL-2018-03-01-VOT-ITM-680793...,[eli/dl/doc/OJQ-8-2018-03-01],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2018-03-01T00:00:00+01:00', 'type'..."
18,eli/dl/event/MTG-PL-2018-03-15,Activity,2018-03-15T23:00:00+01:00,MTG-PL-2018-03-15,"{'es': 'Jueves 15 de marzo de 2018', 'hu': '20...",2018-03-15T01:00:00+01:00,[eli/dl/event/MTG-PL-2018-03-15-VOT-ITM-684523...,[eli/dl/doc/OJQ-8-2018-03-15],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2018-03-15T00:00:00+01:00', 'type'..."
19,eli/dl/event/MTG-PL-2018-04-19,Activity,2018-04-19T23:00:00+02:00,MTG-PL-2018-04-19,"{'cs': 'Čtvrtek, 19. dubna 2018', 'hr': 'četvr...",2018-04-19T01:00:00+02:00,[eli/dl/event/MTG-PL-2018-04-19-VOT-ITM-693997...,[eli/dl/doc/OJQ-8-2018-04-19],def/ep-activities/PLENARY_SITTING,org/ep-8,http://publications.europa.eu/resource/authori...,NaN,NaN,NaN,NaN,NaN,"{'@value': '2018-04-19T00:00:00+02:00', 'type'..."

In [82]:
df.dtypes

id                                    str
type                                  str
activity_date                         str
activity_end_date                     str
activity_id                           str
activity_label                     object
activity_start_date                   str
consists_of                        object
documented_by_a_realization_of     object
had_activity_type                     str
had_excused_person                 object
had_participant_person             object
number_of_attendees               float64
parliamentary_term                    str
recorded_in_a_realization_of       object
hasLocality                           str
was_scheduled_in                   object
dtype: object

In [90]:
df["id"] = df["id"].str.replace("eli/dl/event/", "")

In [ ]:
df.drop(columns=["activity_end_date", "activity_id", "activity_label", "activity_start_date",], inplace=True)

KeyError: "['activity_end_date', 'activity_id', 'activity_label', 'activity_start_date'] not found in axis"

In [94]:
df["meeting_minutes"] = df["documented_by_a_realization_of"]
df.drop(columns=["documented_by_a_realization_of"], inplace=True)
df.head()

,id,type,activity_date,consists_of,had_activity_type,had_excused_person,had_participant_person,number_of_attendees,parliamentary_term,recorded_in_a_realization_of,hasLocality,was_scheduled_in,meeting_minutes
0,MTG-PL-2024-01-18,Activity,2024-01-18,[eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-939931...,def/ep-activities/PLENARY_SITTING,"[person/197683, person/197478, person/132366, ...","[person/4746, person/197772, person/244571, pe...",586.0,org/ep-9,"[eli/dl/doc/PV-9-2024-01-18-ATT, eli/dl/doc/PV...",http://publications.europa.eu/resource/authori...,NaN,[eli/dl/doc/OJQ-9-2024-01-18]
1,MTG-PL-2024-01-25,Activity,2024-01-25,"[eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-5, e...",def/ep-activities/PLENARY_SITTING,"[person/197579, person/124770, person/197396, ...","[person/197840, person/197782, person/197728, ...",340.0,org/ep-9,"[eli/dl/doc/CRE-9-2024-01-25, eli/dl/doc/PV-9-...",http://publications.europa.eu/resource/authori...,NaN,[eli/dl/doc/OJQ-9-2024-01-25]
2,MTG-PL-2024-02-08,Activity,2024-02-08,"[eli/dl/event/MTG-PL-2024-02-08-PVCRE-ITM-11, ...",def/ep-activities/PLENARY_SITTING,"[person/250572, person/197671, person/112748, ...","[person/197563, person/185341, person/197734, ...",578.0,org/ep-9,"[eli/dl/doc/PV-9-2024-02-08-RCV, eli/dl/doc/PV...",http://publications.europa.eu/resource/authori...,NaN,[eli/dl/doc/OJQ-9-2024-02-08]
3,MTG-PL-2024-02-29,Activity,2024-02-29,"[eli/dl/event/MTG-PL-2024-02-29-PVCRE-ITM-14, ...",def/ep-activities/PLENARY_SITTING,"[person/197796, person/124770, person/250572, ...","[person/197590, person/236050, person/197438, ...",567.0,org/ep-9,"[eli/dl/doc/PV-9-2024-02-29-ATT, eli/dl/doc/PV...",http://publications.europa.eu/resource/authori...,NaN,[eli/dl/doc/OJQ-9-2024-02-29]
4,MTG-PL-2024-03-14,Activity,2024-03-14,"[eli/dl/event/MTG-PL-2024-03-14-PVCRE-ITM-13, ...",def/ep-activities/PLENARY_SITTING,"[person/197457, person/96697, person/197542, p...","[person/197584, person/128483, person/197756, ...",566.0,org/ep-9,"[eli/dl/doc/CRE-9-2024-03-14, eli/dl/doc/PV-9-...",http://publications.europa.eu/resource/authori...,NaN,[eli/dl/doc/OJQ-9-2024-03-14]

In [98]:
#Checking what data we are working with
pd.set_option('display.max_colwidth', None)
df["recorded_in_a_realization_of"] = df["recorded_in_a_realization_of"].str.replace("eli/dl/doc/", "")
print(df["recorded_in_a_realization_of"][0:5])

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: recorded_in_a_realization_of, dtype: float64

In [2]:
df.head

NameError: name 'df' is not defined

In [66]:
#Now for the last trick in this notebook I reload the previous data set "all_thursdays.csv"
#I merge that df with my new df of more thursday meetings. We create a bigger data set and then we apply
#a nested api call on those

df_old = pd.read_csv("all_thursdays.csv")

In [67]:
df_combined = pd.concat([df_old, df_more_thursdays], ignore_index=True)

In [69]:
df_combined.drop(columns="Unnamed: 0", inplace=True)
df_combined

,id,type,activity_date,activity_end_date,activity_id,activity_label,activity_start_date,consists_of,documented_by_a_realization_of,had_activity_type,had_excused_person,had_participant_person,number_of_attendees,parliamentary_term,recorded_in_a_realization_of,hasLocality,was_scheduled_in
0,eli/dl/event/MTG-PL-2024-01-18,Activity,2024-01-18,2024-01-18T23:00:00+01:00,MTG-PL-2024-01-18,"{'lt': 'Ketvirtadienis, 2024 m. sausio 18 d.',...",2024-01-18T01:00:00+01:00,['eli/dl/event/MTG-PL-2024-01-18-VOT-ITM-93993...,['eli/dl/doc/OJQ-9-2024-01-18'],def/ep-activities/PLENARY_SITTING,"['person/197683', 'person/197478', 'person/132...","['person/4746', 'person/197772', 'person/24457...",586.0,org/ep-9,"['eli/dl/doc/PV-9-2024-01-18-ATT', 'eli/dl/doc...",http://publications.europa.eu/resource/authori...,NaN
1,eli/dl/event/MTG-PL-2024-01-25,Activity,2024-01-25,2024-01-25T23:00:00+01:00,MTG-PL-2024-01-25,"{'de': 'Donnerstag, 25. Januar 2024', 'it': 'G...",2024-01-25T01:00:00+01:00,"['eli/dl/event/MTG-PL-2024-01-25-PVCRE-ITM-5',...",['eli/dl/doc/OJQ-9-2024-01-25'],def/ep-activities/PLENARY_SITTING,"['person/197579', 'person/124770', 'person/197...","['person/197840', 'person/197782', 'person/197...",340.0,org/ep-9,"['eli/dl/doc/CRE-9-2024-01-25', 'eli/dl/doc/PV...",http://publications.europa.eu/resource/authori...,NaN
2,eli/dl/event/MTG-PL-2024-02-08,Activity,2024-02-08,2024-02-08T23:00:00+01:00,MTG-PL-2024-02-08,"{'sl': 'Četrtek, 8. februar 2024', 'pl': 'Czwa...",2024-02-08T01:00:00+01:00,['eli/dl/event/MTG-PL-2024-02-08-PVCRE-ITM-11'...,['eli/dl/doc/OJQ-9-2024-02-08'],def/ep-activities/PLENARY_SITTING,"['person/250572', 'person/197671', 'person/112...","['person/197563', 'person/185341', 'person/197...",578.0,org/ep-9,"['eli/dl/doc/PV-9-2024-02-08-RCV', 'eli/dl/doc...",http://publications.europa.eu/resource/authori...,NaN
3,eli/dl/event/MTG-PL-2024-02-29,Activity,2024-02-29,2024-02-29T23:00:00+01:00,MTG-PL-2024-02-29,"{'et': 'Neljapäev, 29. veebruar 2024', 'da': '...",2024-02-29T01:00:00+01:00,['eli/dl/event/MTG-PL-2024-02-29-PVCRE-ITM-14'...,['eli/dl/doc/OJQ-9-2024-02-29'],def/ep-activities/PLENARY_SITTING,"['person/197796', 'person/124770', 'person/250...","['person/197590', 'person/236050', 'person/197...",567.0,org/ep-9,"['eli/dl/doc/PV-9-2024-02-29-ATT', 'eli/dl/doc...",http://publications.europa.eu/resource/authori...,NaN
4,eli/dl/event/MTG-PL-2024-03-14,Activity,2024-03-14,2024-03-14T23:00:00+01:00,MTG-PL-2024-03-14,"{'fr': 'Jeudi 14 mars 2024', 'et': 'Neljapäev,...",2024-03-14T01:00:00+01:00,['eli/dl/event/MTG-PL-2024-03-14-PVCRE-ITM-13'...,['eli/dl/doc/OJQ-9-2024-03-14'],def/ep-activities/PLENARY_SITTING,"['person/197457', 'person/96697', 'person/1975...","['person/197584', 'person/128483', 'person/197...",566.0,org/ep-9,"['eli/dl/doc/CRE-9-2024-03-14', 'eli/dl/doc/PV...",http://publications.europa.eu/resource/authori...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,eli/dl/event/MTG-PL-2014-09-18,Activity,"{'@value': '2014-09-18T00:00:00+02:00', 'type'...",2014-09-18T23:00:00+02:00,MTG-PL-2014-09-18,"{'bg': 'Четвъртък, 18 септември 2014', 'fr': '...",2014-09-18T01:00:00+02:00,[eli/dl/event/MTG-PL-2014-09-18-VOT-ITM-373721...,[eli/dl/doc/OJQ-8-2014-09-18],def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-8,NaN,http://publications.europa.eu/resource/authori...,NaN
146,eli/dl/event/MTG-PL-2014-10-23,Activity,"{'@value': '2014-10-23T00:00:00+02:00', 'type'...",2014-10-23T23:00:00+02:00,MTG-PL-2014-10-23,"{'lt': 'Ketvirtadienis, 2014 m. spalio 23 d.',...",2014-10-23T01:00:00+02:00,[eli/dl/event/MTG-PL-2014-10-23-VOT-ITM-383799...,[eli/dl/doc/OJQ-8-2014-10-23],def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-8,NaN,http://publications.europa.eu/resource/authori...,NaN
147,eli/dl/event/MTG-PL-2014-11-13,Activity,"{'@value': '2014-11-13T00:00:00+01:00', 'type'...",2014-11-13T23:00:00+01:00,MTG-PL-2014-11-13,"{'el': 'Πέμπτη 13 Νοεμβρίου 2014', 'pl': 'Czwa...",2014-11-13T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-11-13-VOT-ITM-387061...,[eli/dl/doc/OJQ-8-2014-11-13],def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-8,NaN,http://publications.europa.eu/resource/authori...,NaN
148,eli/dl/event/MTG-PL-2014-11-27,Activity,"{'@value': '2014-11-27T00:00:00+01:00', 'type'...",2014-11-27T23:00:00+01:00,MTG-PL-2014-11-27,"{'da': 'Torsdag den 27. november 2014', 'sk': ...",2014-11-27T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-11-27-VOT-ITM-389743...,[eli/dl/doc/OJQ-8-2014-11-27],def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-8,NaN,http://publications.europa.eu/resource/authori...,NaN
149,eli/dl/event/MTG-PL-2014-12-18,Activity,"{'@value': '2014-12-18T00:00:00+01:00', 'type'...",2014-12-18T23:00:00+01:00,MTG-PL-2014-12-18,"{'et': 'Neljapäev, 18. detsember 2014', 'lt': ...",2014-12-18T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-12-18-VOT-ITM-393876...,[eli/dl/doc/OJQ-8-2014-12-18],def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-8,NaN,http://publications.europa.eu/resource/authori...,NaN

In [72]:
df_combined.sort_values("activity_start_date", inplace=True)
df_combined

,id,type,activity_date,activity_end_date,activity_id,activity_label,activity_start_date,consists_of,documented_by_a_realization_of,had_activity_type,had_excused_person,had_participant_person,number_of_attendees,parliamentary_term,recorded_in_a_realization_of,hasLocality,was_scheduled_in
137,eli/dl/event/MTG-PL-2014-01-16,Activity,"{'@value': '2014-01-16T00:00:00+01:00', 'type'...",2014-01-16T23:00:00+01:00,MTG-PL-2014-01-16,"{'lv': 'Ceturtdiena, 2014. gada 16. janvāris',...",2014-01-16T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-01-16-VOT-ITM-344722...,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-7,NaN,http://publications.europa.eu/resource/authori...,NaN
138,eli/dl/event/MTG-PL-2014-02-06,Activity,"{'@value': '2014-02-06T00:00:00+01:00', 'type'...",2014-02-06T23:00:00+01:00,MTG-PL-2014-02-06,"{'lv': 'Ceturtdiena, 2014. gada 6. februāris',...",2014-02-06T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-02-06-VOT-ITM-345849...,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-7,NaN,http://publications.europa.eu/resource/authori...,NaN
139,eli/dl/event/MTG-PL-2014-02-27,Activity,"{'@value': '2014-02-27T00:00:00+01:00', 'type'...",2014-02-27T23:00:00+01:00,MTG-PL-2014-02-27,"{'hr': 'četvrtak, 27. veljače 2014.', 'de': 'D...",2014-02-27T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-02-27-VOT-ITM-347478...,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-7,NaN,http://publications.europa.eu/resource/authori...,NaN
140,eli/dl/event/MTG-PL-2014-03-13,Activity,"{'@value': '2014-03-13T00:00:00+01:00', 'type'...",2014-03-13T23:00:00+01:00,MTG-PL-2014-03-13,"{'sk': 'Štvrtok, 13. marca 2014', 'de': 'Donne...",2014-03-13T01:00:00+01:00,[eli/dl/event/MTG-PL-2014-03-13-VOT-ITM-347476...,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-7,NaN,http://publications.europa.eu/resource/authori...,NaN
141,eli/dl/event/MTG-PL-2014-04-03,Activity,"{'@value': '2014-04-03T00:00:00+02:00', 'type'...",2014-04-03T23:00:00+02:00,MTG-PL-2014-04-03,"{'lv': 'Ceturtdiena, 2014. gada 3. aprīlis', '...",2014-04-03T01:00:00+02:00,[eli/dl/event/MTG-PL-2014-04-03-VOT-ITM-350849...,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-7,NaN,http://publications.europa.eu/resource/authori...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,eli/dl/event/MTG-PL-2026-10-08,Activity,2026-10-08,2026-10-08T23:00:00+02:00,MTG-PL-2026-10-08,"{'en': 'Thursday, 8 October 2026', 'fi': 'Tors...",2026-10-08T01:00:00+02:00,NaN,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-10,NaN,http://publications.europa.eu/resource/authori...,NaN
38,eli/dl/event/MTG-PL-2026-10-22,Activity,2026-10-22,2026-10-22T23:00:00+02:00,MTG-PL-2026-10-22,"{'fr': 'Jeudi 22 octobre 2026', 'hu': '2026. o...",2026-10-22T01:00:00+02:00,NaN,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-10,NaN,http://publications.europa.eu/resource/authori...,NaN
39,eli/dl/event/MTG-PL-2026-11-12,Activity,2026-11-12,2026-11-12T23:00:00+01:00,MTG-PL-2026-11-12,"{'sl': 'Četrtek, 12. november 2026', 'ro': 'Jo...",2026-11-12T01:00:00+01:00,NaN,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-10,NaN,http://publications.europa.eu/resource/authori...,NaN
40,eli/dl/event/MTG-PL-2026-11-26,Activity,2026-11-26,2026-11-26T23:00:00+01:00,MTG-PL-2026-11-26,"{'hu': '2026. november 26., csütörtök', 'lv': ...",2026-11-26T01:00:00+01:00,NaN,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-10,NaN,http://publications.europa.eu/resource/authori...,NaN
41,eli/dl/event/MTG-PL-2026-12-17,Activity,2026-12-17,2026-12-17T23:00:00+01:00,MTG-PL-2026-12-17,"{'lt': 'Ketvirtadienis, 2026 m. gruodžio 17 d....",2026-12-17T01:00:00+01:00,NaN,NaN,def/ep-activities/PLENARY_SITTING,NaN,NaN,NaN,org/ep-10,NaN,http://publications.europa.eu/resource/authori...,NaN

In [73]:
df_combined.to_csv("all_thursdays.csv")